### ISSUE TITLE
Upper Ring very difficult to remove from bed

### ISSUE THREAD

**Issue by scruss** [makersmakingchange/Open-Wobble-Switch#1]
`OWS_Wand_Ring_Upper_v0.1.stl` is thin, flexible and curves inwards. Consequently it's very hard to remove from the print bed. The typical tools couldn't shift it: had to resort to putting the Prusa print bed in the freezer.

A small outward chamfer to allow a tool underneath to lever the part off would be appreciated.

**Comment by jakemcivor** [comment]
OWS_Wand_Ring_Upper_v0.1.stl was removed in v1.0
